server:
  port: 9000
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: "1.0"

cards:
  message: "Welcome to Bank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald  - product Owner"
    email: "sandra@mantletechsolutions.com"
  onCallSupport:
    - (+44) 617 432-2356
    - (+44) 936 564-8721
